/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * Principal.java
 *
 * Created on 05-abr-2013, 20:15:45
 */
package views;

import java.sql.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Administrador
 */
public class ViewAdmin extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form Principal
     */
    public static String hora, minutos, segundos, ampm;
    Calendar calendario;
    Thread h1;

    public ViewAdmin() {
        initComponents();
        h1 = new Thread(this);
        h1.start();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpescritorio = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        reloj2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblusu = new javax.swing.JLabel();
        reloj = new javax.swing.JLabel();
        ho = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cerrarsecion = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        materias_primas_item = new javax.swing.JMenuItem();
        productos_item = new javax.swing.JMenuItem();
        usuarios_item = new javax.swing.JMenuItem();
        entradas = new javax.swing.JMenu();
        movimientoEntradasMaterias = new javax.swing.JMenuItem();
        entradas_productos_item = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        salidas_materias_item = new javax.swing.JMenuItem();
        salidas_productos_item = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        consultasClientes = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        consultasClientes1 = new javax.swing.JMenuItem();
        reportecliente = new javax.swing.JMenu();
        menuClientesSi = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuClientesNo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Ventas");

        jdpescritorio.setBackground(new java.awt.Color(25, 153, 153));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/car_icon-icons.com_54409.png"))); // NOI18N
        jLabel2.setLabelFor(entradas);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jdpescritorio.add(jLabel2);
        jLabel2.setBounds(850, 220, 130, 130);

        reloj2.setFont(new java.awt.Font("Arial Narrow", 1, 60)); // NOI18N
        reloj2.setForeground(new java.awt.Color(255, 255, 255));
        reloj2.setText("jLabel11");
        jdpescritorio.add(reloj2);
        reloj2.setBounds(480, 30, 290, 80);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/car_23773.png"))); // NOI18N
        jLabel3.setLabelFor(entradas);
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jdpescritorio.add(jLabel3);
        jLabel3.setBounds(250, 220, 130, 130);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1486504829-clipboard-tasks-report-business-checking-verification-list_81387.png"))); // NOI18N
        jLabel4.setLabelFor(entradas);
        jLabel4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jdpescritorio.add(jLabel4);
        jLabel4.setBounds(450, 220, 130, 130);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search_find_client_user_16693.png"))); // NOI18N
        jLabel5.setLabelFor(entradas);
        jLabel5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jdpescritorio.add(jLabel5);
        jLabel5.setBounds(650, 220, 130, 130);

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Reportes");
        jdpescritorio.add(jLabel6);
        jLabel6.setBounds(450, 350, 130, 30);

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Materias prima");
        jdpescritorio.add(jLabel7);
        jLabel7.setBounds(850, 350, 130, 30);

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Productos");
        jdpescritorio.add(jLabel8);
        jLabel8.setBounds(250, 350, 170, 30);

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Usuarios");
        jdpescritorio.add(jLabel9);
        jLabel9.setBounds(650, 350, 130, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/degradados-wallpapers-7.jpg"))); // NOI18N
        jdpescritorio.add(jLabel10);
        jLabel10.setBounds(0, -10, 1840, 1210);

        reloj.setText("jLabel3");

        ho.setText("Hora:");

        jLabel1.setText("Usuario Conectado:");

        jMenu1.setText("Archivo");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        cerrarsecion.setText("Cerrar Sesion");
        cerrarsecion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarsecionActionPerformed(evt);
            }
        });
        jMenu1.add(cerrarsecion);

        salir.setText("Minimizar");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jMenu1.add(salir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Mantenimiento");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        materias_primas_item.setText("Materias prima");
        materias_primas_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materias_primas_itemActionPerformed(evt);
            }
        });
        jMenu2.add(materias_primas_item);

        productos_item.setText("Productos");
        productos_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productos_itemActionPerformed(evt);
            }
        });
        jMenu2.add(productos_item);

        usuarios_item.setText("Usuarios");
        usuarios_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarios_itemActionPerformed(evt);
            }
        });
        jMenu2.add(usuarios_item);

        jMenuBar1.add(jMenu2);

        entradas.setText("Entradas");
        entradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradasActionPerformed(evt);
            }
        });

        movimientoEntradasMaterias.setText("Materias primas");
        movimientoEntradasMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movimientoEntradasMateriasActionPerformed(evt);
            }
        });
        entradas.add(movimientoEntradasMaterias);

        entradas_productos_item.setText("Productos");
        entradas_productos_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradas_productos_itemActionPerformed(evt);
            }
        });
        entradas.add(entradas_productos_item);

        jMenuBar1.add(entradas);

        jMenu3.setText("Salidas");

        salidas_materias_item.setText("Materias primas");
        salidas_materias_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salidas_materias_itemActionPerformed(evt);
            }
        });
        jMenu3.add(salidas_materias_item);

        salidas_productos_item.setText("Productos");
        salidas_productos_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salidas_productos_itemActionPerformed(evt);
            }
        });
        jMenu3.add(salidas_productos_item);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Consultas");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        consultasClientes.setText("Materias primas");
        consultasClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultasClientesActionPerformed(evt);
            }
        });
        jMenu4.add(consultasClientes);

        jMenuItem1.setText("Productos");
        jMenu4.add(jMenuItem1);

        consultasClientes1.setText("Usuarios");
        consultasClientes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultasClientes1ActionPerformed(evt);
            }
        });
        jMenu4.add(consultasClientes1);

        jMenuBar1.add(jMenu4);

        reportecliente.setText("Reportes");

        menuClientesSi.setText("Ingresos del dia");
        menuClientesSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesSiActionPerformed(evt);
            }
        });
        reportecliente.add(menuClientesSi);

        jMenuItem2.setText("Ingresos mensual");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        reportecliente.add(jMenuItem2);

        menuClientesNo.setText("Clientes mensuales");
        menuClientesNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesNoActionPerformed(evt);
            }
        });
        reportecliente.add(menuClientesNo);

        jMenuBar1.add(reportecliente);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(lblusu, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 820, Short.MAX_VALUE))
            .addComponent(jdpescritorio)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ho)
                .addGap(3, 3, 3)
                .addComponent(reloj)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jdpescritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblusu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ho)
                    .addComponent(reloj)
                    .addComponent(jLabel1))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
// TODO add your handling code here:

}//GEN-LAST:event_jMenu1ActionPerformed

private void cerrarsecionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarsecionActionPerformed
// TODO add your handling code here:
    /*LOGGIN principal = new LOGGIN();
    principal.setVisible(true);
    principal.pack();
    this.setVisible(false);
     */
}//GEN-LAST:event_cerrarsecionActionPerformed

private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
// TODO add your handling code here:
    this.dispose();
}//GEN-LAST:event_salirActionPerformed

private void materias_primas_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materias_primas_itemActionPerformed
    MateriasPrima ip = new MateriasPrima();
    jdpescritorio.add(ip);
    ip.show();

}//GEN-LAST:event_materias_primas_itemActionPerformed

private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
// TODO add your handling code here:

}//GEN-LAST:event_jMenu2ActionPerformed

private void entradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradasActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_entradasActionPerformed

private void movimientoEntradasMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movimientoEntradasMateriasActionPerformed
    EntradaMateriasPrimas ip = new EntradaMateriasPrimas();
    jdpescritorio.add(ip);
    ip.show();

}//GEN-LAST:event_movimientoEntradasMateriasActionPerformed

private void menuClientesSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesSiActionPerformed
// TODO add your handling code here:


}//GEN-LAST:event_menuClientesSiActionPerformed

private void consultasClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultasClientesActionPerformed


}//GEN-LAST:event_consultasClientesActionPerformed

private void salidas_materias_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salidas_materias_itemActionPerformed
    SalidaMateriasPrimas ip = new SalidaMateriasPrimas();
    jdpescritorio.add(ip);
    ip.show();

}//GEN-LAST:event_salidas_materias_itemActionPerformed

private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jMenu4ActionPerformed

private void menuClientesNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesNoActionPerformed
// TODO add your handling code here:

}//GEN-LAST:event_menuClientesNoActionPerformed

    private void usuarios_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarios_itemActionPerformed
        Usuarios ip = new Usuarios();

        jdpescritorio.add(ip);
        ip.show();
    }//GEN-LAST:event_usuarios_itemActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void entradas_productos_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradas_productos_itemActionPerformed
        EntradaProductos ip = new EntradaProductos();
        jdpescritorio.add(ip);
        ip.show();
    }//GEN-LAST:event_entradas_productos_itemActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked

    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked

    }//GEN-LAST:event_jLabel4MouseClicked

    private void salidas_productos_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salidas_productos_itemActionPerformed
        SalidasProductos ip = new SalidasProductos();
        jdpescritorio.add(ip);
        ip.show();
    }//GEN-LAST:event_salidas_productos_itemActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

    }//GEN-LAST:event_jLabel2MouseClicked

    private void productos_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productos_itemActionPerformed
        Productos ip = new Productos();
        jdpescritorio.add(ip);
        ip.show();
    }//GEN-LAST:event_productos_itemActionPerformed

    private void consultasClientes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultasClientes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultasClientes1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ViewAdmin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cerrarsecion;
    private javax.swing.JMenuItem consultasClientes;
    private javax.swing.JMenuItem consultasClientes1;
    private javax.swing.JMenu entradas;
    private javax.swing.JMenuItem entradas_productos_item;
    private javax.swing.JLabel ho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    public static javax.swing.JDesktopPane jdpescritorio;
    public static javax.swing.JLabel lblusu;
    private javax.swing.JMenuItem materias_primas_item;
    private javax.swing.JMenuItem menuClientesNo;
    private javax.swing.JMenuItem menuClientesSi;
    private javax.swing.JMenuItem movimientoEntradasMaterias;
    private javax.swing.JMenuItem productos_item;
    public static javax.swing.JLabel reloj;
    private javax.swing.JLabel reloj2;
    private javax.swing.JMenu reportecliente;
    private javax.swing.JMenuItem salidas_materias_item;
    private javax.swing.JMenuItem salidas_productos_item;
    private javax.swing.JMenuItem salir;
    private javax.swing.JMenuItem usuarios_item;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        Thread ct = Thread.currentThread();
        while (ct == h1) {
            calcula();
            reloj.setText(hora + ":" + minutos + ":" + segundos + " " + ampm);
            reloj2.setText(hora + ":" + minutos + ":" + segundos + " " + ampm);
            try {
                Thread.sleep(1000);
            } catch (Exception e) {
            }
        }
    }

    private void calcula() {
        Calendar calendario = new GregorianCalendar();
        java.util.Date fechahoraActual = new java.util.Date();
        calendario.setTime(fechahoraActual);
        ampm = calendario.get(Calendar.AM_PM) == Calendar.AM ? "AM" : "PM";
        if (ampm.equals("PM")) {
            int h = calendario.get(Calendar.HOUR_OF_DAY) - 12;
            hora = h > 9 ? "" + h : "0" + h;
        } else {
            hora = calendario.get(Calendar.HOUR_OF_DAY) > 9 ? "" + calendario.get(Calendar.HOUR_OF_DAY) : "0" + calendario.get(Calendar.HOUR_OF_DAY);
        }
        minutos = calendario.get(Calendar.MINUTE) > 9 ? "" + calendario.get(Calendar.MINUTE) : "0" + calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND) > 9 ? "" + calendario.get(Calendar.SECOND) : "0" + calendario.get(Calendar.SECOND);
    }
}
